### ISSUE TITLE
Keen-CLI treats CSV as one long string

### ISSUE THREAD

**Issue by wetzler** [keen/keen-cli#22]
I have a scenario where two seemingly identical files have different results during CSV import.

It appears that Keen-CLI is treating one file as one very long header, and the other one is fine. There is some issue with the way carriage returns are encoded which is confusing Keen-CLI.

![screen shot 2016-02-05 at 10 52 32 am](https://cloud.githubusercontent.com/assets/1840448/12855845/9d5a23a4-cbf6-11e5-9141-013410ef5678.png)

**Comment by dkador** [comment]
i'd suggest uploading the two files somehow.

**Comment by wetzler** [comment]
It turns out the main problem the customer was facing was due to un-ecoded carriage returns in their data, so it's not really the CLI to blame. Going to close this issue.
