### ISSUE TITLE
Bulk Add using json file

### ISSUE THREAD

**Issue by alexchuvand** [keen/keen-cli#26]
When trying to bulk add using a json file, it looks like the events in the json file needs to all be in one line. 

If my events.json has the format below:

[
    {
        "apple": "sauce"
    },
    {
        "banana": "pudding"
    },
    {
        "cherry": "pie"
    }
]

running this command 
`keen events:add -c signup -f events.json`
throws this error:
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/json/common.rb:156:in `parse': 409: unexpected token at '' (JSON::ParserError)

if I put everything in a single line like below, the bulk add works.
[{ "apple" : "sauce" }, { "banana" : "pudding" }, { "cherry" : "pie" }]

Is that intended ?

**Comment by joshed-io** [comment]
That's the way it works, yeah. It was originally designed to process files with this structure:

```
{ "a": "b" }
{ "a": "b" }
{ "a": "b" }
```
But it also supports the lines if they're surrounded by `[]`.

The code update doesn't look difficult but not trivial either. Using a tool like [jq](https://stedolan.github.io/jq/) or a node script commands might be a good workaround.

**Comment by alexchuvand** [comment]
Thanks for the quick response. 

I used jq to format my json file and write the output to another json file using this command.

`cat events.json | jq . -c  > test.json`

After that I run the command line:
`keen events:add -c tests --file test.json`

It worked. Problem Solved.
